spring:
    application:
        name: aurora-logger
    cloud:
        inetutils:
          default-ip-address:  127.0.0.1

#开启自动部署
devtools:
  restart:
    enabled: true

server:
  port: 1500

eureka:
  instance:
    hostname:  ${spring.cloud.inetutils.default-ip-address}
    ##以ip注册到注册中心
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.inetutils.default-ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.inetutils.default-ip-address}:8671/eureka/




