server:
  port: 1600
spring:
    application:
        name: aurora-mq
    cloud:
        inetutils:
          default-ip-address:  127.0.0.1
    ### rabbitMQ 配置
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest

#开启自动部署
devtools:
  restart:
    enabled: true
## eureka 客户端配置
eureka:
  instance:
    hostname:  ${spring.cloud.inetutils.default-ip-address}
    ##以ip注册到注册中心
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.inetutils.default-ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.inetutils.default-ip-address}:8671/eureka/





